name: karaparty_bot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - discord.py
      - pynacl
      - pyyaml
      - python-dotenv
      - google-auth
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-api-python-client
      - selenium
      - webdriver-manager